from pathlib import Path
import pandas as pd
import random
import json
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from olympus import Dataset
from olympus.campaigns import Campaign
from atlas.planners.gp.planner import GPPlanner


class Atlas_LSPR:
    def __init__(self, root_data: Path, seed: int=123, target: int=700):
        self.seed = seed
        self.seed_everything()
        self.dataset_name = f'AuNRs_{self.__class__.__name__}'
        root_data = Path(root_data)
        root_olympus_dataset = Path('./olympus/src/olympus/datasets') / ('dataset_' + self.dataset_name)
        data = pd.read_excel(root_data, header=0)
        self.target = target
        self.raw_data = self.preprocess(data, root_olympus_dataset)

    def seed_everything(self):
        random.seed(self.seed)

    def preprocess(self, data: pd.DataFrame, root_olympus_dataset: Path) -> pd.DataFrame:
        root_olympus_dataset.mkdir(parents=True, exist_ok=True)
        data = data[(data['wave_name']<'20230501') & (data['2nd_peak_wave'] >0) & (data['label']=='H')]
        data = data.drop(['wave_name', 
                          'label', 
                          'peak_num'], axis=1)  # useless string
        data = data.drop(['超纯水/mL', 
                          'CTAB(s)/g', 
                          'NaOL(s)/g', 
                          '1mM HAuCl4/mL',
                          'AA/mL', 
                          '晶种/mL'], axis=1)  # useless same param
        data = data.drop(['2nd_peak_width', 
                          '2nd_peak_ratio', 
                          '2nd_peak_diff'], axis=1)  # useless metric
        data = data.rename(columns={'4mM AgNO3/mL': 'AgNO3', '3.6542M 盐酸/mL': 'HCL'})
        data, self.obj_name = self.heuristic(data)
        data.reset_index(drop=True, inplace=True)
        data.to_csv(root_olympus_dataset / 'data.csv', index=False, header=False)
        self.preprocess_config(data, root_olympus_dataset / 'config.json')
        self.preprocess_desc(data, root_olympus_dataset / 'description.txt')
        return data

    def heuristic(self, data: pd.DataFrame):
        obj_name = 'heuristic_value'
        data['2nd_peak_wave'] = 1.0 - (abs(data['2nd_peak_wave'] - self.target) / 1000)
        data = data.rename(columns={'2nd_peak_wave': obj_name})
        return data, obj_name

    def anti_heuristic(self, heuristic_value):
        ori_name = f'2nd_peak_wave_diff_with_{self.target}'
        ori_value = (1.0 - heuristic_value) * 1000
        return ori_value, ori_name

    def preprocess_config(self, data: pd.DataFrame, root_config: Path):
        agno3, hcl = data['AgNO3'], data['HCL']
        config = {
            "constraints": {
                "parameters":   "none",
                "measurements": "positive",
                "known": "no"
                },
            "parameters": [
                    {"name": "AgNO3", "type": "continuous", "low": min(agno3), "high": max(agno3)},
                    {"name": "HCL", "type": "continuous", "low": min(hcl), "high": max(hcl)}
                ],
            "measurements": [
                    {"name": self.obj_name, "type": "continuous"}
                ],
            "default_goal": "maximize"
        }
        with open(root_config, 'w', encoding='utf-8') as f:
            json.dump(config, f, ensure_ascii=False, indent=4)

    def preprocess_desc(self, data: pd.DataFrame, root_desc: Path):
        contents = [
            'Dataset generated by C-LAB.', 
            '',
            '=========================================',
            '\t\t\t\tSummary',
            '-----------------------------------------',
            f'\tNumber of Samples\t\t\t{len(data)}',
            '\tDimensionality\t\t\t\t2',
            '\tFeatures:',
            '\t\tAgNO3\t\t\t\tcontinuous',
            '\t\tHCL\t\t\t\t\tcontinuous',
            '\tTargets:',
            f'\t{self.obj_name}\t\tcontinuous',
            '========================================='
        ]
        with open(root_desc, 'w') as f:
            f.write('\n'.join(contents))

    def run(self, epoch=10):
        dataset = Dataset(kind=self.dataset_name, random_seed=self.seed)
        param_space = dataset.param_space
        campaign = Campaign()
        campaign.set_param_space(param_space)
        planner = GPPlanner(
            goal='maximize', 
            init_design_strategy='random',
            num_init_design=3,
            use_descriptors=False,
            batch_size=1,
            value_space=dataset.value_space,
            random_seed=self.seed
        )
        planner.set_param_space(param_space)
        while len(campaign.observations.get_values()) < epoch:
            samples = planner.recommend(campaign.observations) # ask planner for batch of parameters
            for sample in samples:
                _, measurement = self.measure_nearest_sample(dataset, sample) # make an experimental measurement
                campaign.add_observation(sample, measurement) # tell planner about most recent observation
        params = campaign.get_params()
        objs = campaign.get_values()
        df_alkox = pd.DataFrame({
            'AgNO3': params[:, 0].flatten(),
            'HCL': params[:, 1].flatten(),
            self.obj_name: objs[:].flatten()
        })
        best_step = df_alkox[self.obj_name].argmax()
        print('*'*60)
        print(f'    [Best Step]: {best_step}')
        agno3, hcl, obj = df_alkox.iloc[best_step]
        ori_value, ori_name = self.anti_heuristic(obj)
        print(f'\tAgNO3: {agno3:.4f}, HCL: {hcl:.4f}')
        print(f'\t{self.obj_name}: {obj:.4f}')
        print(f'\t{ori_name}: {ori_value:.4f}')
        print('*'*60)
        print(df_alkox)
        print('*'*60)
        self.vis(df_alkox)

    def measure_nearest_sample(self, dataset, sample):
        '''
        Measure and return the value the is closes to the queried sample.
        '''
        sample = sample.to_array()
        dataset_points = dataset.data.to_numpy()[:,:-1]
        output_points = dataset.data.to_numpy()[:,-1]
        distances = np.sqrt(np.sum((dataset_points - sample)**2, axis=1))
        min_idx = np.argmin(distances)
        return dataset_points[min_idx], output_points[min_idx]

    def vis(self, df_alkox: pd.DataFrame):
        fig, axes = plt.subplots(1, 1)
        # process the dataframes
        df_alkox['Planner'] = 'GP'
        df_alkox['Best value'] = df_alkox[self.obj_name].cummax()
        # plot the best trace
        sns.lineplot(data=df_alkox, x=df_alkox.index, y='Best value', hue='Planner', ax=axes)
        axes.set_xlabel('Evaluations')
        axes.set_title('Atlas Bayesian Optimization of AuNRs')
        plt.show()


class Atlas_FWHM(Atlas_LSPR):
    def heuristic(self, data: pd.DataFrame):
        obj_name = 'heuristic_value'
        data['2nd_peak_wave'] = 1.0 - (data['2nd_peak_wave'] / 1000)
        data = data.rename(columns={'2nd_peak_wave': obj_name})
        return data, obj_name

    def anti_heuristic(self, heuristic_value):
        ori_name = '2nd_peak_wave'
        ori_value = (1.0 - heuristic_value) * 1000
        return ori_value, ori_name


class Atlas_RATIO(Atlas_LSPR):
    def heuristic(self, data: pd.DataFrame):
        obj_name = 'heuristic_value'
        data['2nd_peak_wave'] = data['2nd_peak_wave'] / 4.0
        data = data.rename(columns={'2nd_peak_wave': obj_name})
        return data, obj_name

    def anti_heuristic(self, heuristic_value):
        ori_name = '2nd_peak_wave'
        ori_value = heuristic_value * 4.0
        return ori_value, ori_name


if __name__ == '__main__':
    root_data = './data/20230320_20230628_result.xlsx'
    atlas = Atlas_FWHM(root_data, seed=1234)
    atlas.run(epoch=10)
